Create view for mobile mode
teknologi-umum/tgif pull request #32
Opened 2023-03-16 07:56 UTC by rijalBinHusen

I just do hide and show between _sidebar_ and _chat content_ to make view on mobile better #20.

2023-03-17 06:16 UTC, elianiva requested changes

2023-03-17 06:16 UTC, elianiva commented on src/components/Seo.astro
> +const thumbnail: string = Astro.site + "thumbnail.png";
```suggestion
const thumbnail = Astro.site + "/thumbnail.png";
```

2023-03-17 06:16 UTC, elianiva commented on src/pages/chat/[slug].astro
> +const url: string = Astro.site + Astro.url.pathname.replace("/", "");
```suggestion
const url = Astro.site + Astro.url.pathname.replace("/", "");
```

2023-03-17 06:16 UTC, elianiva commented on src/scripts/mobile-mode-switcher.ts
> +window.addEventListener("resize", () => switchToMobile());
kenapa switchnya pake JS? plain css ngga cukup?

2023-03-17 07:44 UTC, rijalBinHusen commented on src/scripts/mobile-mode-switcher.ts
> +window.addEventListener("resize", () => switchToMobile());
Waduw, gimana itu caranya pak?
Pakai _@media screen_ kah?
Tapi tampilnya betul gitu nggak? bergantian antar sidebar || chatbox, atau tetep tampil dua duanya sidebar && chatbox pas dimobile modenya?

2023-03-19 01:49 UTC, elianiva commented on src/scripts/mobile-mode-switcher.ts
> +window.addEventListener("resize", () => switchToMobile());
iya pake @media

ini tombol homenya mending pake icon, style buttonnya samain kek yg lain, terus dibikin floating aja biar ngga motong lebar chatnya
![image](https://user-images.githubusercontent.com/51877647/226149219-a59c3ede-ed17-4c2c-8d3b-0362ab3cd950.png)

terus ini kudu dikasih limit lebarnya biar ngga nabrak
![image](https://user-images.githubusercontent.com/51877647/226149260-455d5666-6353-49e6-b83d-7fac7498cea8.png)

2023-03-23 02:11 UTC, rijalBinHusen commented
Seperti ini kurang lebih cuplikanya pak 🙏
![software-testing-_-t_2023-2-23](https://user-images.githubusercontent.com/67273416/227080786-46e79507-353b-4949-8cbe-9246e15c2a0a.gif)

2023-03-23 02:55 UTC, aldy505 approved these changes
Looks great!

2023-03-23 02:55 UTC, aldy505 commented on src/components/Seo.astro
>  const summarySEO = props?.summary || "Kutipan chat dari berbagai group telegram progaming indonesia";
```suggestion
const summarySEO = props?.summary || "Kutipan chat dari berbagai group Telegram programming indonesia";
```

mumpung keliatan

2023-03-23 02:55 UTC, aldy505 commented on src/components/Seo.astro
>  	: ["Telegram", "Group programing", "indonesia"].join(", ");
```suggestion
	: ["Telegram", "Group programming", "indonesia"].join(", ");
```

2023-03-23 07:44 UTC, elianiva approved these changes
jago

2023-03-23 07:54 UTC, merged