belajar ilmu kebal itu dulu yang ngajarin kebal juga ga?
teknologi-umum/tgif pull request #35
Opened 2023-03-19 12:25 UTC by WahidinAji

kalo bulan bisa ngomong, serem sih.

2023-03-19 12:33 UTC, aldy505 requested changes

2023-03-19 12:33 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +  },
bagian ini bisa di hapus

2023-03-19 12:33 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
sebenernya bisa start dari conversation ini aja

2023-03-19 12:33 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
tapi ini included

2023-03-19 12:33 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
dan ini juga di keep

2023-03-19 12:33 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
berakhir disini

2023-03-19 12:34 UTC, elianiva approved these changes
apakah benar, ikan berkepala lele itu ada

2023-03-19 12:51 UTC, WahidinAji commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
ga terlalu dikit ntar?

tapi gpp sih, dikit kalo sampe.


ok

2023-03-19 12:55 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
emang dikit kan

2023-03-19 14:44 UTC, aldy505 requested changes
dikit lagi ji

2023-03-19 14:44 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
dari sini

2023-03-19 14:44 UTC, aldy505 commented on public/chats/dependency-injection-in-a-nutshell/result.json
> +		},
sampe sini (dari comment sebelomnya), hapus aja

2023-03-25 07:22 UTC, aldy505 approved these changes

2023-03-25 07:23 UTC, aldy505 commented
file name lu harusnya exported.json, bukan results.json. CI nya fail

2023-03-25 07:24 UTC, WahidinAji commented
yg nge-merge siapa pack? @aldy505

2023-03-25 07:24 UTC, aldy505 commented
CI nya fail pak. benerin dulu itu filename @WahidinAji

2023-03-25 07:25 UTC, WahidinAji commented
> CI nya fail pak. benerin dulu itu filename @WahidinAji

wait, sekalian gw lupa nambahin metadata

2023-03-25 07:31 UTC, WahidinAji commented
hmm masih failed

2023-03-25 07:33 UTC, aldy505 commented
coba jalanin di local dulu. cek dimana errornya

2023-03-25 07:42 UTC, WahidinAji commented
> coba jalanin di local dulu. cek dimana errornya

https://github.com/teknologi-umum/tgif/pull/35/files#diff-05ddb0c55259c531ac24851fd5528815a3e80826422655d4ba933cedc9605d74R170-R204

yg bikin error

2023-03-25 08:24 UTC, merged