Add couple conversation
teknologi-umum/tgif pull request #38
Opened 2023-03-27 08:43 UTC by rijalBinHusen

Percakapan legend: _coorporate speak_

2023-03-28 00:01 UTC, aldy505 requested changes

2023-03-28 00:01 UTC, aldy505 commented on public/chats/coorporate-speak/metadata.json
> +	"tags": ["random", "sepak", "coorporate"],
sepak?

2023-03-28 00:01 UTC, aldy505 commented on public/chats/perlu-belajar-assembly/exported.json
> +		},
delete aja

2023-03-28 00:01 UTC, aldy505 commented on public/chats/perlu-belajar-assembly/exported.json
> +		},
delete aja

2023-03-28 00:01 UTC, aldy505 commented on public/chats/perlu-belajar-assembly/exported.json
> +		},
delete aja

2023-03-28 00:31 UTC, rijalBinHusen commented on public/chats/coorporate-speak/metadata.json
> +	"tags": ["random", "sepak", "coorporate"],
Bruh, teliti betul 🥇

2023-03-28 00:38 UTC, rijalBinHusen commented
Saya ndak paham errornya ini pak, penyebabnya apaan yak

2023-03-28 03:10 UTC, WahidinAji commented on public/chats/coorporate-speak/metadata.json
> +	"date": "2022-06-05"
ini tanggalnya dibuat tanggal PR aja ;D

2023-03-28 03:10 UTC, WahidinAji commented on public/chats/coorporate-speak/metadata.json
> +	"slug": "coorporate-speak",
sebenernya, dora bingung ini percakapan dimulai dari mana

2023-03-28 03:10 UTC, WahidinAji commented on public/chats/perlu-belajar-assembly/metadata.json
> +	"slug": "perlu-belajar-assembly",
btw, prefer PR per diskusi ketimbang couple2

2023-03-28 04:14 UTC, rijalBinHusen commented on public/chats/coorporate-speak/metadata.json
> +	"date": "2022-06-05"
Wahh, baru tau tuh saya, kirain tanggal percakapanya pak

2023-03-28 05:25 UTC, aldy505 commented on public/chats/coorporate-speak/metadata.json
> +	"date": "2022-06-05"
itu harusnya tanggal percakapan

2023-03-28 05:25 UTC, aldy505 commented
> Saya ndak paham errornya ini pak, penyebabnya apaan yak

@rijalBinHusen no problem itu, masalah code coverage doang

2023-03-28 05:25 UTC, aldy505 approved these changes

2023-06-03 11:20 UTC, aldy505 commented
@elianiva mau review?

2023-06-04 12:10 UTC, elianiva approved these changes
mucho texto

2023-06-04 12:10 UTC, merged